services:
  - type: web
    name: spotify-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd /opt/render/project/src && gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true 